<h2>Ajouter un contact</h2>

<?=$this->form()->openTag($contactForm)?>
    <div class="form-group">
        <?=$this->formLabel($contactForm->get('prenom')) ?>
        <?=$this->formElement($contactForm->get('prenom')->setAttribute('class', 'form-control')) ?>
        <?=$this->formElementErrors($contactForm->get('prenom')) ?>
    </div>
    <div class="form-group">
        <?=$this->formLabel($contactForm->get('nom')) ?>
        <?=$this->formElement($contactForm->get('nom')->setAttribute('class', 'form-control')) ?>
        <?=$this->formElementErrors($contactForm->get('nom')) ?>
    </div>
    <div class="form-group">
        <?=$this->formLabel($contactForm->get('email')) ?>
        <?=$this->formElement($contactForm->get('email')->setAttribute('class', 'form-control')) ?>
        <?=$this->formElementErrors($contactForm->get('email')) ?>
    </div>
    <div class="form-group">
        <?=$this->formLabel($contactForm->get('telephone')) ?>
        <?=$this->formElement($contactForm->get('telephone')->setAttribute('class', 'form-control')) ?>
        <?=$this->formElementErrors($contactForm->get('telephone')) ?>
    </div>
    <div>
        <button type="submit" class="btn btn-primary">Ajouter</button>
    </div>
<?=$this->form()->closeTag()?>

<?php $this->headStyle()->captureStart(); ?>
/*#contact label {
    display: block;
}*/
<?php $this->headStyle()->captureEnd(); ?>