<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <?=$this->headTitle('AddressBook')->setSeparator(' - ')?>
  
        <link rel="stylesheet" href="<?=$this->basePath('css/bootstrap.css')?>">
        <?=$this->headLink()?>
        
        <?=$this->headStyle()?>
        
        <?=$this->headScript()?>
        
        <?=$this->headMeta()?>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?=$this->url('contact')?>">AddressBook</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="<?=$this->url('contact')?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Contacts <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?=$this->url('contact')?>">Lister</a></li>
                                <li><a href="<?=$this->url('contact/add')?>">Ajouter</a></li>
                            </ul>
                        </li>
                    </ul> 
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">
            <?=$this->content?>
        </div>
        <script src="<?=$this->basePath('js/jquery.min.js')?>"></script>
        <script src="<?=$this->basePath('js/bootstrap.js')?>"></script>
        <?=$this->inlineScript()?>
    </body>
</html>
